NibblesBookApp/urls.py
from django.urls import path
from NibblesBookApp import views

app_name = 'NibblesBookApp'

urlpatterns = [
    path('book/<int:book_id>', views.get_book, name='get_book'),
    path('genre/<str:genre>', views.get_genre, name='get_genre'),
    path('author/<int:author_id>', views.get_author, name='get_author'),
    path('search/', views.search, name='search'),
    path('api/books/', views.book_list, name='api_book_list'),
    path('api/author/', views.author_list, name='api_author_list'),
]

NibblesBookProject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from NibblesBookApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('nibbles/', include('NibblesBookApp.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

NibblesBookApp/models.py
from django.db import models
from djmoney.models.fields import MoneyField


class Author(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    image = models.CharField(max_length=50, default='static/images/authors/')
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    about = models.TextField(max_length=1000, default='None')

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    def full_name(self):
        return self.first_name + ' ' + self.last_name


class Publisher(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Store(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    name = models.CharField(max_length=80)

    def __str__(self):
        return self.name


class Book(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    image = models.CharField(max_length=300, default='static/images/books/')
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    pages = models.PositiveSmallIntegerField()
    description = models.TextField(max_length=900)
    genre = models.CharField(max_length=30)
    isbn = models.BigIntegerField()
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    date = models.DateTimeField(null=True, blank=True)
    store = models.ManyToManyField(Store)

    def __str__(self):
        return self.title

    ''' get average rating of a book '''
    def get_avg_rating(self, book_id):
        book = Book.objects.get(id=book_id)
        rating_sum = 0
        all_reviews = book.review_set.all()
        num_of_reviews = all_reviews.count()
        for ratings in all_reviews:
            rating_sum = rating_sum + ratings.rating

        if num_of_reviews == 0:
            return "%.1f" % 0
        return "%.1f" % (rating_sum / num_of_reviews)


class Format(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    format_type = models.CharField(max_length=40)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    price = MoneyField(max_digits=10, decimal_places=2, default_currency='USD')

    def __str__(self):
        return self.format_type


class Review(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    reviewer = models.CharField(max_length=50)
    date = models.DateTimeField(blank=True, null=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(default=1)
    title = models.CharField(max_length=30, default='Good read!')
    content = models.TextField(max_length=800, default='This was a good book to read!')

    def __str__(self):
        return self.book.title

NibblesBookApp/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from NibblesBookApp import models
from django.db.models import Q
from rest_framework.decorators import api_view
from rest_framework.response import Response
from NibblesBookApp import serializers
from rest_framework import status

''' generate the number of loops '''
def generate_number_of_loops(num):
    if num % 5 == 0:
        return num // 5

    return int(num // 5) + 1

''' return a list of books in chunks by a certain number '''
def return_books_by_number(queryset, number):
    book_in_number = []
    start = 0
    end = number
    loops = generate_number_of_loops(len(queryset))

    for i in range(loops):
        book_in_number.append(queryset[start:end])
        start += number
        end += number
    return book_in_number


def index(request):
    queryset = models.Book.objects.all()
    book_in_sixes = return_books_by_number(queryset, 6)
    context = {'book_in_sixes': book_in_sixes}
    return render(request, 'index.html', context)


def get_book(request, book_id):
    rating_range = range(1, 6)
    book = get_object_or_404(models.Book, id=book_id)
    book_formats = book.format_set.all()
    book_reviews = book.review_set.all()
    recommended_books = models.Book.objects.filter(Q(genre__iexact=book.genre) and ~Q(id=book.id))[:5]

    context = {'book': book,
               'book_formats': book_formats,
               'book_reviews': book_reviews,
               'recommended_books': recommended_books,
               'rating_range': rating_range,'avg': book.get_avg_rating(book_id)}

    return render(request, 'book.html', context)


def get_author(request, author_id):
    queryset = get_object_or_404(models.Author, id=author_id)
    author_books = queryset.book_set.all()
    book_in_fives_by_author = return_books_by_number(author_books, 5)
    context = {'queryset': queryset,
               'book_in_fives_by_author': book_in_fives_by_author}

    return render(request, 'author.html', context)


def get_genre(request, genre):
    queryset = models.Book.objects.filter(genre=genre)
    context = {'queryset': queryset, 'genre': genre}
    return render(request, 'genres.html', context)


def search(request):
    query = request.GET.get('query')
    queryset = []
    exists = False

    if request.method == 'GET':
        if query:
            queryset = models.Book.objects.filter(Q(title__iexact=query) |
                                              Q(title__icontains=query))
            exists = queryset.exists()

    context = {'queryset': queryset, 'exists': exists, 'query': query}
    return render(request, 'search.html', context)


def about(request):
    template = 'about.html'
    return render(request, template)




######################### Rest functions #############################


@api_view(['GET', 'POST'])
def book_list(request):
    if request.method == 'GET':
        queryset = models.Book.objects.all()
        serialize = serializers.BookSerializer(queryset, many=True)
        return Response(serialize.data)
    else:
        return Response(status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'POST'])
def author_list(request):
    if request.method == 'GET':
        queryset = models.Author.objects.all()
        serialize = serializers.AuthorSerializer(queryset, many=True)
        return Response(serialize.data)
    else:
        return Response(status=status.HTTP_400_BAD_REQUEST)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Nibbles - about the awesome website{% endblock %}

{% block body %}

     <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">About Nibbles</h1>
          <p class="lead text-muted" align="justify">
              Thanks for visiting this website. Nibbles is a fun book web application built using django. It's a project inspired by the Barnes and Noble website.
              Allow me to shade some light on how this project came to be. From time to time programmers ask themselves what project to work on next.
              The thing is, most want to work on original ideas, which isn't bad at all especially if you are trying to run a startup but it's pretty
              difficult to come up with an original idea and it can be time consuming. If you want to practice the skills you have just learned after
              taking a course or just want to create something to add to your portfolio, originality shouldn't be a top concern. It's better to spend time mimicking
              another app out there than spending so much time thinking about an idea (again if your are not part of a startup). So it's about practicing the skills
              you learned. Check out this article that explains the idea better:
              <a href="https://www.freecodecamp.org/news/the-secret-to-unlimited-project-ideas/" target="_blank">here</a>
          </p>
          <p>Contact: <a href="mailto:jackslaighter@email.com">jackslaighter@gmail.com</a></p>
          <p>GitHub:<a href="https://github.com/Munanga" target="_blank">link</a></p>
        </div>
  </section>


{% endblock %}

templates/author.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Nibbles - {{ queryset.full_name }}{% endblock %}

{% block body %}

    <div class="container">
        <h3 align="center">{{ queryset.full_name }}</h3>
        <!-- Author picture -->
        <div class="row" style="margin-top: 2%">
            <div class="col-md-4 offset-md-2">
                <figure class="figure">
                    <div>
                        <img src="/{{ queryset.image }}" class="figure-img img-fluid shadow-lg" alt="{{ queryset.full_name }}" style="width:350px;height:350px;">
                    </div>
                </figure>
            </div>
            <!-- About Author -->
            <div class="col-md-4">
                <h4>About the Author</h4>
                <p align="justify">{{ queryset.about }}</p>
            </div>
        </div>

        <!-- Books by Author -->

        <h5 align="center">Books by {{ queryset.full_name }}</h5>

        <hr size="5">
        {% if book_in_fives_by_author %}
            {% for list in book_in_fives_by_author %}
                <div class="row ">
                    {% for book in list %}
                        <div class="col-md-2">
                            <figure class="figure">
                                <a href="{% url 'NibblesBookApp:get_book' book.id %}">
                                  <div class="nang">
                                  <img src="/{{ book.image }}" class="figure-img img-fluid" alt="{{ book.title }}" style="width:132px;height:210px;">
                                  </div>
                                </a>
                                <figcaption class="figure-caption">
                                    <a href="{% url 'NibblesBookApp:get_book' book.id %}" style="color: black"><div align="left">{{ book.title }}</div></a>
                                    {{ book.date |date:'M Y' }}<br>
                                    <span class="blog-post-meta">By <a href="{% url 'NibblesBookApp:get_author' book.author_id %}">{{ book.author }}</a></span>
                                </figcaption>
                            </figure>
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        {% else %}
             <p>No books to display yet</p>
        {% endif %}

    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>{% block title %}{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/blog/">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/sticky-footer/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <!-- Script for star rating -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="{% static 'css/style.css' %}" rel="stylesheet">

  </head>

  <body class="body">

    <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="{% url 'about' %}">About</a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="{% url 'index' %}"><img src="{% static 'images/icon/1.png' %}" style="width:50px;height:40px;">Nibbles</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <form method="get" action="{% url 'NibblesBookApp:search' %}" class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </div>

      </header>

      <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
          <a class="p-2 text-muted" href="{% url 'NibblesBookApp:get_genre' 'Fiction' %}">Fiction</a>
          <a class="p-2 text-muted" href="{% url 'NibblesBookApp:get_genre' 'Romance' %}">Romance</a>
          <a class="p-2 text-muted" href="{% url 'NibblesBookApp:get_genre' 'Religion' %}">Religion</a>
          <a class="p-2 text-muted" href="{% url 'NibblesBookApp:get_genre' 'Horror' %}">Horror</a>
          <a class="p-2 text-muted" href="{% url 'NibblesBookApp:get_genre' 'Classics' %}">Classics</a>
          <a class="p-2 text-muted" href="{% url 'NibblesBookApp:get_genre' 'Mystery' %}">Mystery</a>
          <a class="p-2 text-muted" href="{% url 'NibblesBookApp:get_genre' 'Historical' %}">Historical</a>
          <a class="p-2 text-muted" href="{% url 'NibblesBookApp:get_genre' 'Fantasy' %}">Fantasy</a>
          <a class="p-2 text-muted" href="{% url 'NibblesBookApp:get_genre' 'Philosophy' %}">Philosophy</a>
          <a class="p-2 text-muted" href="{% url 'NibblesBookApp:get_genre' 'Nonfiction' %}">Nonfiction</a>
          <a class="p-2 text-muted" href="{% url 'NibblesBookApp:get_genre' 'Adventure' %}">Adventure</a>
          <a class="p-2 text-muted" href="{% url 'NibblesBookApp:get_genre' 'Animals' %}">Animals</a>
        </nav>
      </div>


       {% block body %}

       {% endblock %}




   </div>
         <!-- Page Footer -->
        <footer class="footer">
          <div>
            <span class="text-muted"><img src="{% static 'images/icon/1.png' %}" style="width:20px;height:20px;">Nibbles - A Munsaka project</span>
          </div>
        </footer>

    </body>


</html>

templates/book.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Nibbles - {{ queryset.title }}{% endblock %}

{% block body %}

    <div class="container">
        {% if book %}
            <!-- Display Book details -->
            <div class="book_details">
                <div class="row">
                <!-- Display Book Image -->
                    <div class="col-md-4 offset-md-2">
                        <div class="large_book_image">
                            <figure class="figure">
                                <div class="nang">
                                  <img src="/{{ book.image }}" class="figure-img img-fluid shadow-lg" alt="{{ book.title }}" style="width:290px;height:411px;"><br>
                                </div>
                            </figure>
                        </div>
                    </div>

                    <!-- Display details -->
                    <div class="col-md-6">
                        <span class="book_title">{{ book.title }}</span> <br> by
                        <a href="{% url 'NibblesBookApp:get_author' book.author_id %}">{{ book.author.full_name }}</a><br>
                        <hr size="10">
                        <span>Available Formats</span><br>

                        <div class="details">
                            <div class="row">
                            {% for format in book_formats %}
                                    <div class="col-sm-3">
                                        <div class="format_border">
                                            {{ format.format_type }}<br>
                                            <div class="nang" style="color: red">{{ format.price }}</div>
                                         </div>
                                    </div>
                            {% endfor %}
                            </div>

                        </div>
                        <br>
                        <span>Available at the following stores🏬:</span><br>
                        <ul>
                            {% for store in book.store.all %}
                                <li>{{ store }}</li>
                            {% endfor %}
                        </ul>


                        <hr size="10">
                        <span style="color: steelblue"><a href="#reviews">{{ book.review_set.count }} Customer Reviews</a></span>
                        <p><h5>Average rating: <span style="color: darkorange">{{ avg }}</span></h5></p>
                    </div>
                </div>
            </div>


             <!-- Book Summary section -->
            <br>
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <div class="jumbotron text-Black">
                        <h2 class="book_text" align="center">Summary</h2>
                        <p>{{ book.description }}</p>
                    </div>
                </div>
            </div>


            <br>
            <!-- Product Details -->
            <div class="row">
                <div class="col">
                    <div>
                        <h4 align="center">Product Details</h4>
                        <p align="center">
                            <table class="table col-md-4 offset-md-4">
                              <thead>
                                <tr>
                                  <th scope="col">ISBN-13:</th>
                                  <th scope="col">{{ book.isbn }}</th>
                                </tr>
                              </thead>
                              <tbody>
                                <tr>
                                  <th scope="row">Publisher:</th>
                                  <td>{{ book.publisher }}</td>
                                </tr>
                                <tr>
                                  <th scope="row">Publication date:</th>
                                  <td>{{ book.date|date:'M j Y' }}</td>
                                </tr>
                                <tr>
                                  <th scope="row">Genre:</th>
                                  <td>{{ book.genre }}</td>
                                </tr>
                                <tr>
                                  <th scope="row">Pages:</th>
                                  <td>{{ book.pages }}</td>
                                </tr>
                              </tbody>
                            </table>
                        </p>

                    </div>
                </div>

            </div>


            <br>
            <!-- Book reviews -->
            <div class="row">
                <div class="col-md-8 offset-md-2">
                   <h4 align="center" class="book_text" id="reviews">Reviews</h4>
                    <hr size="10">
                    <div class="row">

                        {% for reviews in book_reviews %}
                        <div class="col-md-6">
                            <p align="justify"><img src="{% static 'images/profile/Avatar_empty.png' %}">&nbsp;{{ reviews.reviewer }}<br>
                                <span class="font-weight-light">{{ reviews.date| timesince }} ago</span><br>
                                {% for rating in rating_range %}
                                    {% if reviews.rating >= rating %}
                                        <span class="fa fa-star checked"></span>
                                    {% endif %}
                                {% endfor %}
                            </p>
                        </div>

                        <div class="col-md-6">
                            <p align="justify" style="font-size: smaller">{{ reviews.content }}</p>
                                <hr size="10">
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <br>
            <!-- Other Books  -->
             <div class="row">
                 <div class="col-md-8 offset-md-2">
                    <h4 align="center">You may also like:</h4>

                     <div class="row justify-content-center">

                        {% for book in recommended_books %}
                            <div class="col">
                                <figure class="figure">
                                    <a href="{% url 'NibblesBookApp:get_book' book.id %}">
                                      <div class="nang">
                                      <img src="/{{ book.image }}" class="figure-img img-fluid" alt="{{ book.title }}" style="width:132px;height:210px;">
                                      </div>
                                    </a>
                                    <figcaption class="figure-caption">
                                        {{ book.date |date:'M Y' }}<br>
                                        <span class="blog-post-meta">By <a href="{% url 'NibblesBookApp:get_author' book.author_id %}">{{ book.author }}</a></span>
                                    </figcaption>
                                </figure>
                            </div>
                        {% endfor %}

                     </div>

                 </div>
             </div>

        {% else %}
            <p>Sorry cannot find the book you are looking for</p>
        {% endif %}

    </div>

{% endblock %}

templates/genres.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Nibbles - {{ queryset.title }}{% endblock %}

{% block body %}

    <h3 align="center" style="margin-top: 2%;margin-bottom: 2%">{{ genre }}</h3>


    {% for book in queryset %}

        <div class="row">
            <div class="col-md-5" align="right">
                <hr size="4" class="col-md-3" align="right">
                <figure class="figure">
                    <a href="{% url 'NibblesBookApp:get_book' book.id %}">
                      <div class="nang">
                      <img src="/{{ book.image }}" class="figure-img img-fluid" alt="{{ book.title }}" style="width:132px;height:210px;">
                      </div>
                    </a>
                    <figcaption class="figure-caption">
                        {{ book.date |date:'M Y' }}<br>
                        <span class="blog-post-meta">By <a href="{% url 'NibblesBookApp:get_author' book.author_id %}">{{ book.author }}</a></span>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-7"><hr size="5">
                <p>{{ book.description }}</p>
            </div>
        </div>

        {% endfor %}

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Nibbles - A place for book lovers{% endblock %}

{% block body %}

    <div class="jumbotron p-4 p-md-7 text-white rounded bg-dark">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h1 class="display-4 font-italic" align="center">Our featured book</h1>
            </div>
            <div class="col-md-6">
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                <img src="{% static 'images/books/JaneEyre.jpg' %}" style="width:160px;height:240px;" class="nang">
            </div>
            <div class="col-md-10">
                <p class="lead my-3">
                    <h4 style="">Jane Eyre</h4>
                     Orphaned as a child, Jane has felt an outcast her whole young life. Her courage is tested once again when she arrives at Thornfield Hall, where she has been hired by the brooding, proud Edward Rochester to care for his ward Adèle.
                      Jane finds herself drawn to his troubled yet kind spirit. She falls in love. Hard.
                  </p>
                  <p class="lead mb-0"><a href="{% url 'NibblesBookApp:get_book' 12 %}" class="text-white font-weight-bold">Read more..</a></p>
            </div>
        </div>


    </div>


    {% if book_in_sixes %}
        {% for list in book_in_sixes %}
            <div class="row ">
                {% for book in list %}
                    <div class="col-md-2">
                        <figure class="figure">
                            <a href="{% url 'NibblesBookApp:get_book' book.id %}">
                              <div class="nang">
                              <img src="{{ book.image }}" class="figure-img img-fluid" alt="{{ book.title }}" style="width:132px;height:210px;">
                              </div>
                            </a>
                            <figcaption class="figure-caption">
                                <a href="{% url 'NibblesBookApp:get_book' book.id %}" style="color: black"><div align="left">{{ book.title }}</div></a>
                                {{ book.date |date:'M Y' }}<br>
                                <span class="blog-post-meta">By <a href="{% url 'NibblesBookApp:get_author' book.author_id %}">{{ book.author }}</a></span>
                            </figcaption>
                        </figure>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    {% else %}
        <p>No books to display yet</p>
    {% endif %}



{% endblock %}

templates/publisher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Nibbles - {{ queryset.title }}{% endblock %}

{% block body %}

    <div class="container">

        <div class="row">
            <div class="col-md-6">
                {% if exists %}
                    <h4 align="center" style="margin-top: 2%;margin-bottom: 2%">Showing book title results for "<b>{{query}}</b>"</h4>

                    {% for book in queryset %}
                        <div class="row">
                            <div class="col-md-5" align="right">
                                <hr size="4" class="col-md-3" align="right">
                                <figure class="figure">
                                    <h5>{{ book.title }}</h5>
                                    <a href="{% url 'NibblesBookApp:get_book' book.id %}">
                                      <div class="nang">
                                      <img src="/{{ book.image }}" class="figure-img img-fluid" alt="{{ book.title }}" style="width:132px;height:210px;">
                                      </div>
                                    </a>
                                    <figcaption class="figure-caption">
                                        {{ book.date |date:'M Y' }}<br>
                                        <span class="blog-post-meta">By <a href="{% url 'NibblesBookApp:get_author' book.id %}">{{ book.author }}</a></span>
                                    </figcaption>
                                </figure>
                            </div>
                            <div class="col-md-7"><hr size="5">
                                <p align="justify">{{ book.description }}</p>
                            </div>
                        </div>

                    {% endfor %}
                {% else %}
                    <p>Sorry no search results for "<b>{{query}}</b>"</p>
                {% endif %}
            </div>
        </div>

    </div>

{% endblock %}